### ISSUE TITLE
interconnected slider

### ISSUE THREAD

**Issue by diana1357** [AskiaADX/Slider#6]
Hi

When I have an interconnected slider with two slides, if I have the first slider at 0 and the second at maximum value (in this example 100), the second slider cannot be moved anymore, only the first slider is movable.
![slider](https://user-images.githubusercontent.com/20987595/31231557-1abdaeac-a9df-11e7-943e-2d860a71f754.png)
I'm attaching the qex with my question - please ignore the slide colours .
[InterconnectedSlider.zip](https://github.com/AskiaADX/Slider/files/1359593/InterconnectedSlider.zip)

**Comment by Djedj** [comment]
Hi Diana,

I improved the behaviour of the interconnected slider and it's available in this repo (v2.0.2)

Let us know if it's ok for you ?

**Comment by diana1357** [comment]
Thank you it looks good!
However I noticed one more thingI noticed.
I have "hide handle at start"="no" but both handles are hidden when the questions loads. When I select an answer on one of the sliders, the other slider still remains hidden.
![slider1](https://user-images.githubusercontent.com/20987595/31284236-e0bbbf60-aaaf-11e7-98e1-f48ada3b7c24.PNG)

![slider](https://user-images.githubusercontent.com/20987595/31283572-e5ec9e52-aaad-11e7-82e5-a9cec3405153.png)

**Comment by Djedj** [comment]
Hi Diana,

I just updated the control to v2.0.3. Should be fixed. Can you tell us ?

Best Regards

**Comment by diana1357** [comment]
Hi!
I've just tested using v2.0.3 but still get the same issue. I've rebuilt the page and after doing so the slider is not shown at all. Not sure what I'm doing wrong, so I've attached the qex.
[InterconnectedSlider.zip](https://github.com/AskiaADX/Slider/files/1368152/InterconnectedSlider.zip)

**Comment by Djedj** [comment]
Hi Diana,

I just tried and it worked. See animated gif below:

![slider](https://user-images.githubusercontent.com/11887298/31334815-2926a408-acf0-11e7-865f-3fcc30243952.gif)

**Comment by diana1357** [comment]
it could be my version of askia Design. From your gif I can also see that when you select a value on one slider, the other slider doesn't move (not until you select it)

**Comment by Djedj** [comment]
Hi Diana,

For the second slider not moving it's normal cause there is no value selected.

**Comment by diana1357** [comment]
When one slider is selected, the other one should move accordingly. This is how it was behaving in previous versions of the adc, and it also makes sense for the respondent.
I've attached the previous version of the slider, as example.
[InterconnectedSlider_old.zip](https://github.com/AskiaADX/Slider/files/1368531/InterconnectedSlider_old.zip)

**Comment by Djedj** [comment]
Hi Diana,

I modified the adc (v2.0.4) to use the Hide Handle parameter for that so if you show the handle at start then all the cursor will move.

**Comment by diana1357** [comment]
thanks it works :+1:
